# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    my_parameter: "parametr ok"
    my_parameter_env: 'my APP_ENV: %env(APP_ENV)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\MyPractices\Domain\BookingRepoInterface:
        class: App\Repository\BookingRepository
        arguments:
            - '@doctrine'

    MyServices:
        class: App\MyPractices\Domain\MyService
        arguments:
            - '@BookingRepoInterface'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    redis_cache_service:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        arguments:
            - '@redis'
    redis:
        class: Redis
        public: false
        calls:
            - method: connect
              arguments:
                  - 'mycache'
